---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    name: hello-world
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: gcr.io/cicd-gke-demo/go-hello-world:master-12d9cbc
        ports:
        - containerPort: 8080
